//! Tokenizer error types — the single error type for the BMS tokenizer.

use std::fmt;
use std::num::ParseFloatError;
use std::num::ParseIntError;

use thiserror::Error;

/// Errors that can occur during BMS tokenization.
///
/// Variants are categorised into four groups:
/// - **Structural** — the line itself has invalid syntax.
/// - **Numeric** — a numeric field failed to parse (std errors, owned).
/// - **Invalid value** — the input is not a recognised value for its domain.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum BmsTokenizeError<'a> {
    /// The measure number in a channel line is not a valid 3-digit value.
    #[error("invalid measure number: \"{0}\"")]
    InvalidMeasure(&'a str),
    /// The channel number in a channel line is not a valid 2-digit value.
    #[error("invalid channel number: \"{0}\"")]
    InvalidChannel(&'a str),

    /// An integer field could not be parsed.
    #[error("invalid integer: {0}")]
    InvalidInteger(String),
    /// A float field could not be parsed.
    #[error("invalid float: {0}")]
    InvalidFloat(String),

    /// The input is not a recognised value for its domain.
    ///
    /// When `detail` is empty string, no additional hint is appended.
    #[error("invalid value \"{value}\" for {context}{detail}")]
    InvalidValue {
        /// The header command name (e.g., `"#PLAYER"`).
        context: &'static str,
        /// The raw input that failed to parse.
        value: &'a str,
        /// Contextual hint (e.g., `" (expected 1-5)"`) or `""` for none.
        detail: &'static str,
    },
}

/// The input could not be parsed as the expected BMS value type.
///
/// Returned by [`std::str::FromStr`] impls generated by `#[derive(BmsValue)]`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParseBmsValueError;

impl fmt::Display for ParseBmsValueError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "invalid BMS value")
    }
}

impl std::error::Error for ParseBmsValueError {}

impl From<ParseIntError> for BmsTokenizeError<'_> {
    fn from(e: ParseIntError) -> Self {
        BmsTokenizeError::InvalidInteger(e.to_string())
    }
}

impl From<ParseFloatError> for BmsTokenizeError<'_> {
    fn from(e: ParseFloatError) -> Self {
        BmsTokenizeError::InvalidFloat(e.to_string())
    }
}
