//! Player 热路径基准测试。
//!
//! 量化以下操作的耗时，为优化决策提供数据（而非猜测）：
//!
//! - `TimingTrack::duration_to_tick` —— `O(n)` 线性扫描（P1 前的旧路径）
//! - `TimingCache::duration_to_tick` —— `O(log n)` 二分（P1 + O(log n) 重写后的路径）
//! - `TimingCache::tick_to_duration` —— `O(log n)` 二分
//! - `Player::advance` —— 播放循环每帧调用
//!
//! 运行：`cargo bench -p bmsrs-player`

// criterion 宏生成的入口函数无文档，工作区 missing_docs=deny 需在此豁免。
#![expect(
    missing_docs,
    reason = "bench harness entry points generated by criterion macros"
)]

use std::num::NonZeroU8;
use std::time::Duration;

use bmsrs_chart::{
    BpmChange, Chart, ChartData, ChartInfo, Event, Lane, NoteKind, NoteSide, SongInfo, StopEvent,
    TimingCache, TimingTrack,
};
use bmsrs_player::Player;
use criterion::{BenchmarkId, Criterion, black_box, criterion_group, criterion_main};

/// 默认节拍分辨率（每四分音符的脉冲数）。
const RESOLUTION: u64 = 240;
/// 第一个常规按键（1P 侧），用 `NonZeroU8::MIN` 避免 `unwrap`。
const KEY1: NonZeroU8 = NonZeroU8::MIN;
/// 每帧增量（约 60 FPS）。
const FRAME: Duration = Duration::from_nanos(16_666_667);

/// 构建一个含 `n` 个音符、若干 BPM 变更与停止的谱面。
///
/// 模拟真实谱面密度：每拍约一个音符，每隔固定间隔插入 BPM 变更与停止，
/// 使计时轨非平凡。
#[expect(
    clippy::cast_precision_loss,
    reason = "indices fit in f64 for benchmark sizes"
)]
fn build_chart(n: usize) -> Chart {
    let mut events = Vec::with_capacity(n + n / 50 + 4);

    for i in 0..n {
        let tick = (i as u64) * RESOLUTION; // 每拍一个音符
        events.push(Event::Note {
            tick,
            side: NoteSide::P1,
            lane: Lane::Key(KEY1),
            kind: NoteKind::Normal,
            audio_index: None,
            ext: (),
        });
    }

    // 每隔 50 个音符插入一次 BPM 变更。
    let mut bpm_changes = Vec::new();
    for i in (0..n).step_by(50) {
        let tick = (i as u64) * RESOLUTION;
        let bpm = 120.0 + ((i % 200) as f64);
        events.push(Event::Bpm { tick, bpm });
        bpm_changes.push(BpmChange { tick, bpm });
    }

    // 每隔 100 个音符插入一次停止。
    let mut stops = Vec::new();
    for i in (0..n).step_by(100) {
        let tick = (i as u64) * RESOLUTION;
        events.push(Event::Stop {
            tick,
            duration: RESOLUTION,
        });
        stops.push(StopEvent {
            tick,
            duration: RESOLUTION,
        });
    }

    events.sort_by_key(Event::sort_key);

    let timing = TimingTrack::new(120.0, bpm_changes, stops);

    Chart {
        song: SongInfo::default(),
        chart: ChartInfo::default(),
        data: ChartData {
            resolution: RESOLUTION,
            timing,
            judge_multiplier: 1.0,
            life_multiplier: 1.0,
            events,
            audio_assets: vec![],
        },
    }
}

/// 基准：`TimingTrack::duration_to_tick`（`O(n)` 旧路径，P1 前用于 advance）。
///
/// 目标取谱面 90% 处的时刻，使 `O(n)` 扫描处理绝大多数事件
/// （反映后期游玩中每帧的最坏情况）。
fn bench_timing_track_duration_to_tick(c: &mut Criterion) {
    let mut group = c.benchmark_group("duration_to_tick / timing_track [O(n)]");
    for &n in &[500usize, 2000, 8000] {
        let chart = build_chart(n);
        let cache = TimingCache::new(&chart.data.timing, chart.data.resolution);
        let last_tick = chart.data.last_tick();
        let target = cache.tick_to_duration(last_tick * 9 / 10);
        group.bench_with_input(BenchmarkId::from_parameter(n), &n, |b, _| {
            b.iter(|| {
                black_box(
                    chart
                        .data
                        .timing
                        .duration_to_tick(target, chart.data.resolution),
                )
            });
        });
    }
    group.finish();
}

/// 基准：`TimingCache::duration_to_tick`（`O(log n)` 新路径，P1 后用于 advance）。
fn bench_timing_cache_duration_to_tick(c: &mut Criterion) {
    let mut group = c.benchmark_group("duration_to_tick / timing_cache [O(log n)]");
    for &n in &[500usize, 2000, 8000] {
        let chart = build_chart(n);
        let cache = TimingCache::new(&chart.data.timing, chart.data.resolution);
        let last_tick = chart.data.last_tick();
        let target = cache.tick_to_duration(last_tick * 9 / 10);
        group.bench_with_input(BenchmarkId::from_parameter(n), &n, |b, _| {
            b.iter(|| black_box(cache.duration_to_tick(target)));
        });
    }
    group.finish();
}

/// 基准：`TimingCache::tick_to_duration`（`O(log n)`）。
fn bench_timing_cache_tick_to_duration(c: &mut Criterion) {
    let mut group = c.benchmark_group("tick_to_duration / timing_cache [O(log n)]");
    for &n in &[500usize, 2000, 8000] {
        let chart = build_chart(n);
        let cache = TimingCache::new(&chart.data.timing, chart.data.resolution);
        let tick = chart.data.last_tick() * 9 / 10;
        group.bench_with_input(BenchmarkId::from_parameter(n), &n, |b, _| {
            b.iter(|| black_box(cache.tick_to_duration(tick)));
        });
    }
    group.finish();
}

/// 基准：`Player::advance`（播放循环每帧调用，P1 修复的热路径）。
///
/// 预先将 player seek 到谱面 90% 处，测量后期游玩中每帧的最坏情况。
fn bench_player_advance(c: &mut Criterion) {
    let mut group = c.benchmark_group("player::advance (per-frame)");
    for &n in &[500usize, 2000, 8000] {
        let chart = build_chart(n);
        let cache = TimingCache::new(&chart.data.timing, chart.data.resolution);
        let mut player = Player::new(chart);
        let last_tick = player.chart().data.last_tick();
        player.seek(cache.tick_to_duration(last_tick * 9 / 10));
        group.bench_with_input(BenchmarkId::from_parameter(n), &n, |b, _| {
            b.iter(|| player.advance(FRAME));
        });
    }
    group.finish();
}

criterion_group!(
    benches,
    bench_timing_track_duration_to_tick,
    bench_timing_cache_duration_to_tick,
    bench_timing_cache_tick_to_duration,
    bench_player_advance,
);
criterion_main!(benches);
