[package]
name = "bms-tokenizer"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
authors.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
readme.workspace = true

[dependencies]
thiserror.workspace = true
derive_more.workspace = true
itertools.workspace = true
bms-tokenizer-derive.workspace = true

[dev-dependencies]
insta.workspace = true
proptest.workspace = true

[lib]

[lints]
workspace = true
