[package]
name = "bmson-def"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
authors.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
readme.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
derive_more.workspace = true
serde_with.workspace = true

[dev-dependencies]
chumsky.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lib]

[lints]
workspace = true
