[package]
name = "bmson-processor"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
authors.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
bmson-def.workspace = true
bmsrs-chart.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lib]

[lints]
workspace = true
