[package]
name = "bms-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
authors.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
readme.workspace = true

[dependencies]
bms-tokenizer.workspace = true

[lib]

[lints]
workspace = true
